export default {
  id: '0fae83ea-6082-4055-aef9-9b195a8d7c25',
  provideAlternative: false,
  provideUnavailabilityReason: true,
  qualificationResult: 'Qualified',
  productOfferingQualificationItemContainer: [
    {
      id: 'c5eb5223-ca86-4232-bb28-096819d4f7a8',
      processContext: 'ACQ',
      qualificationItemResult: 'Qualified',
      productOfferingQualificationItem: [
        {
          id: null,
          action: null,
          qualificationItemResult: null,
          eligibiltyUnavailabilityReason: null,
          state: null,
          terminationError: null,
          productOfferingQualificationItem: null,
          productOffering: {
            id: '0a16a1d5-6499-417f-9c73-23b8ca891f42',
            lifecycleStatus: 'Active',
            name: 'Bundle Discount - 5',
            version: '1.0',
            category: [
              {
                id: '4e6f75d2-6c8b-42e3-b58e-6029e7c9dd2c',
                href:
                  'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/4e6f75d2-6c8b-42e3-b58e-6029e7c9dd2c',
                name: 'MobileSubscription',
                version: null,
                '@baseType': null,
                '@type': null,
                '@refferedType': null,
                '@schemaLocation': null,
              },
            ],
            productOfferingPrice: [
              {
                id: 'de1f3a4d-3d84-41ba-989e-47ca34e43bf0',
                href: null,
                description: 'RecurringDiscount-5',
                lifecycleStatus: 'Active',
                name: 'RecurringDiscount-5',
                percentage: 0,
                priceType: 'Recurring',
                recurringChargePeriodLength: 1,
                recurringChargePeriodType: 'Month',
                version: '1.0',
                bundledPopRelationship: null,
                price: { unit: 'Pound', value: 5 },
                tax: [
                  {
                    taxCategory: 'Govt. tax',
                    taxRate: 0,
                    taxAmount: { unit: 'Pound', value: 0 },
                    basetype: null,
                    type: null,
                  },
                ],
                money: null,
                code: 'OP63',
                constraint: null,
                place: null,
                popRelationship: null,
                pricingLogicAlgorithm: null,
                productOfferingTerm: null,
                unitOfMeasure: { amount: 1, units: 'Unit' },
                validFor: {
                  endDateTime: '2020-07-09T05:29Z',
                  startDateTime: '2020-06-09T05:29Z',
                },
                externalID: null,
                offset: 0,
                processContext: null,
                bundle: false,
                isBundle: false,
                lastUpdate: null,
                '@baseType': 'ProductOfferingPrice',
                '@type': 'ProductOfferingPrice',
                specCharValueUse: null,
                createdBy: 'catalog admin',
                createdOn: '2020-06-09T05:29Z',
                lastUpdatedBy: null,
                productOffering: null,
              },
            ],
            validFor: {
              endDateTime: '2020-07-09T05:29Z',
              startDateTime: '2020-06-09T05:29Z',
            },
            sellable: true,
          },
          '@type': 'Allowed',
          '@baseType': null,
          '@schemaLocation': null,
        },
        {
          id: null,
          action: null,
          qualificationItemResult: null,
          eligibiltyUnavailabilityReason: null,
          state: null,
          terminationError: null,
          productOfferingQualificationItem: null,
          productOffering: {
            id: '1bf9ec00-d6bb-4768-800c-52dfbe06839d',
            description: 'Unique benefits and special status',
            lifecycleStatus: 'Active',
            name: 'Premium',
            version: '1.0',
            category: [
              {
                id: '4e6f75d2-6c8b-42e3-b58e-6029e7c9dd2c',
                href:
                  'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/4e6f75d2-6c8b-42e3-b58e-6029e7c9dd2c',
                name: 'MobileSubscription',
                version: null,
                '@baseType': null,
                '@type': null,
                '@refferedType': null,
                '@schemaLocation': null,
              },
            ],
            productOfferingPrice: [
              {
                id: '3bfdd7e5-8945-4a32-9c16-0161057931ae',
                href: null,
                description: null,
                lifecycleStatus: 'Active',
                name: 'Monthly Recurring Price',
                percentage: null,
                priceType: 'Recurring',
                recurringChargePeriodLength: 12,
                recurringChargePeriodType: 'MONTH',
                version: '1.0',
                bundledPopRelationship: null,
                price: { unit: 'Dollar', value: 35 },
                tax: null,
                money: null,
                code: 'OP187',
                constraint: null,
                place: null,
                popRelationship: null,
                pricingLogicAlgorithm: null,
                productOfferingTerm: null,
                unitOfMeasure: null,
                validFor: {
                  endDateTime: '2020-07-31T09:53:00.001Z',
                  startDateTime: '2020-07-01T09:53:00.001Z',
                },
                externalID: null,
                offset: 1,
                processContext: [
                  {
                    id: 'ba2a859c-2324-4274-a086-0b149f58e195',
                    name: 'ACQ',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/ba2a859c-2324-4274-a086-0b149f58e195',
                  },
                  {
                    id: '29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                    name: 'ILSBLU',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                  },
                  {
                    id: '10626e51-3fb5-4909-8310-e667e3caecb6',
                    name: 'Retention',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/10626e51-3fb5-4909-8310-e667e3caecb6',
                  },
                  {
                    id: 'd320935a-ab3d-49f7-a289-be33dcf2b304',
                    name: 'Regrade',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/d320935a-ab3d-49f7-a289-be33dcf2b304',
                  },
                ],
                bundle: false,
                isBundle: false,
                lastUpdate: '2020-07-01T09:53:00.001Z',
                '@baseType': 'ProductOfferingPrice',
                '@type': 'ProductOfferingPrice',
                specCharValueUse: null,
                createdBy: 'catalog admin',
                createdOn: '2020-07-01T09:53:00.001Z',
                lastUpdatedBy: 'catalog admin',
                productOffering: null,
              },
            ],
            validFor: {
              endDateTime: '2020-07-31T09:39:00.001Z',
              startDateTime: '2020-07-01T09:39:00.001Z',
            },
          },
          '@type': 'Allowed',
          '@baseType': null,
          '@schemaLocation': null,
        },
        {
          id: null,
          action: null,
          qualificationItemResult: null,
          eligibiltyUnavailabilityReason: null,
          state: null,
          terminationError: null,
          productOfferingQualificationItem: null,
          productOffering: {
            id: '4fed40a3-1c41-4ee5-a069-34946f62cf78',
            href:
              'http://demo-vnext.tmbmarble.com/api/catalog-projection/v1/productOffering/4fed40a3-1c41-4ee5-a069-34946f62cf78',
            description: 'iPhone 11 White',
            lifecycleStatus: 'Active',
            name: 'iPhone 11 White',
            version: '1.0',
            category: [
              {
                id: '0a4f8169-d15e-4f9b-a460-bf5c3a40c70f',
                href:
                  'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/0a4f8169-d15e-4f9b-a460-bf5c3a40c70f',
                name: 'Handset',
                version: null,
                '@baseType': null,
                '@type': null,
                '@refferedType': null,
                '@schemaLocation': null,
              },
            ],
            productOfferingPrice: [
              {
                id: '6c0c0fe8-eb2b-4c37-8d45-3e139998a556',
                href: null,
                description: 'MRP Price',
                lifecycleStatus: 'Active',
                name: 'MRP  Price',
                percentage: null,
                priceType: 'OneTime',
                recurringChargePeriodLength: null,
                recurringChargePeriodType: null,
                version: '1.0',
                bundledPopRelationship: null,
                price: { unit: 'Dollar', value: 450 },
                tax: null,
                money: null,
                code: 'OP150',
                constraint: null,
                place: null,
                popRelationship: null,
                pricingLogicAlgorithm: null,
                productOfferingTerm: null,
                unitOfMeasure: null,
                validFor: {
                  endDateTime: '2020-07-30T00:34:00.001Z',
                  startDateTime: '2020-06-30T00:34:00.001Z',
                },
                externalID: null,
                offset: 0,
                processContext: [
                  {
                    id: '29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                    name: 'ILSBLU',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                  },
                  {
                    id: 'ba2a859c-2324-4274-a086-0b149f58e195',
                    name: 'ACQ',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/ba2a859c-2324-4274-a086-0b149f58e195',
                  },
                ],
                bundle: false,
                isBundle: false,
                lastUpdate: '2020-06-30T00:34:00.001Z',
                '@baseType': 'ProductOfferingPrice',
                '@type': 'ProductOfferingPrice',
                specCharValueUse: null,
                createdBy: 'catalog admin',
                createdOn: '2020-06-30T00:34:00.001Z',
                lastUpdatedBy: 'catalog admin',
                productOffering: null,
              },
            ],
            validFor: {
              endDateTime: '2020-07-29T19:03:00.001Z',
              startDateTime: '2020-06-29T19:03:00.001Z',
            },
          },
          '@type': 'Allowed',
          '@baseType': null,
          '@schemaLocation': null,
        },
        {
          id: null,
          action: null,
          qualificationItemResult: null,
          eligibiltyUnavailabilityReason: null,
          state: null,
          terminationError: null,
          productOfferingQualificationItem: null,
          productOffering: {
            id: '525b7fd9-a466-49a3-bfc2-865af4da3767',
            href:
              'http://demo-vnext.tmbmarble.com/api/catalog-projection/v1/productOffering/525b7fd9-a466-49a3-bfc2-865af4da3767',
            lifecycleStatus: 'Active',
            name: 'aPhone Red',
            version: '1.0',
            category: [
              {
                id: 'cc8026c8-180f-49fc-9311-de587ad647a8',
                href:
                  'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/cc8026c8-180f-49fc-9311-de587ad647a8',
                name: 'HandsetLowEnd',
                version: '1.0',
                '@baseType': null,
                '@type': null,
                '@refferedType': null,
                '@schemaLocation': null,
              },
            ],
            productOfferingPrice: [
              {
                id: '40fc108d-4ca7-4faa-8dde-cc416f5f0dee',
                href:
                  'http://demo-vnext.tmbmarble.com/api/catalog-projection/v1/productOfferingPrice/40fc108d-4ca7-4faa-8dde-cc416f5f0dee',
                description: null,
                lifecycleStatus: 'Active',
                name: 'Upfrond 10',
                percentage: 0,
                priceType: 'OneTime',
                recurringChargePeriodLength: 0,
                recurringChargePeriodType: null,
                version: '1.0',
                bundledPopRelationship: null,
                price: { unit: 'Pound', value: 10 },
                tax: [
                  {
                    taxCategory: 'Govt. tax',
                    taxRate: 0,
                    taxAmount: { unit: 'Pound', value: 0 },
                    basetype: null,
                    type: null,
                  },
                ],
                money: null,
                code: 'OP39',
                constraint: null,
                place: null,
                popRelationship: null,
                pricingLogicAlgorithm: null,
                productOfferingTerm: null,
                unitOfMeasure: { amount: 1, units: 'Unit' },
                validFor: {
                  endDateTime: '2021-07-05T03:00:00.001Z',
                  startDateTime: '2020-06-05T03:00:00.001Z',
                },
                externalID: null,
                offset: 1,
                processContext: [
                  {
                    id: 'ba2a859c-2324-4274-a086-0b149f58e195',
                    name: 'ACQ',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/ba2a859c-2324-4274-a086-0b149f58e195',
                  },
                ],
                bundle: false,
                isBundle: false,
                lastUpdate: '2020-07-15T09:36:00.001Z',
                '@baseType': 'ProductOfferingPrice',
                '@type': 'ProductOfferingPrice',
                specCharValueUse: null,
                createdBy: 'catalog admin',
                createdOn: '2020-06-05T03:00:00.001Z',
                lastUpdatedBy: 'Catalog Admin',
                productOffering: {
                  id: '525b7fd9-a466-49a3-bfc2-865af4da3767',
                  href:
                    'http://demo-vnext.tmbmarble.com/api/catalog-projection/v1/productOffering/525b7fd9-a466-49a3-bfc2-865af4da3767',
                  name: 'aPhone Red',
                  version: '1.0',
                },
              },
            ],
            validFor: {
              endDateTime: '2020-07-03T22:53Z',
              startDateTime: '2020-06-03T22:53Z',
            },
            sellable: true,
          },
          '@type': 'Allowed',
          '@baseType': null,
          '@schemaLocation': null,
        },
        {
          id: null,
          action: null,
          qualificationItemResult: null,
          eligibiltyUnavailabilityReason: null,
          state: null,
          terminationError: null,
          productOfferingQualificationItem: null,
          productOffering: {
            id: 'efc66e06-8961-49f2-93b5-9a8c6881f2ba',
            description: 'iPhone 11 Pro Max',
            lifecycleStatus: 'Active',
            name: 'iPhone 11 Pro Max',
            version: '1.0',
            category: [
              {
                id: '0a4f8169-d15e-4f9b-a460-bf5c3a40c70f',
                href:
                  'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/0a4f8169-d15e-4f9b-a460-bf5c3a40c70f',
                name: 'Handset',
                version: null,
                '@baseType': null,
                '@type': null,
                '@refferedType': null,
                '@schemaLocation': null,
              },
            ],
            productOfferingPrice: [
              {
                id: '303c2231-b7b0-4699-8064-2df7a10d0c20',
                href: null,
                description: 'MRP Price',
                lifecycleStatus: 'Active',
                name: 'MRP Price',
                percentage: null,
                priceType: 'OneTime',
                recurringChargePeriodLength: null,
                recurringChargePeriodType: null,
                version: '1.0',
                bundledPopRelationship: null,
                price: { unit: 'Dollar', value: 788 },
                tax: null,
                money: null,
                code: 'OP148',
                constraint: null,
                place: null,
                popRelationship: null,
                pricingLogicAlgorithm: null,
                productOfferingTerm: null,
                unitOfMeasure: null,
                validFor: {
                  endDateTime: '2020-07-30T00:26:00.001Z',
                  startDateTime: '2020-06-30T00:26:00.001Z',
                },
                externalID: null,
                offset: 0,
                processContext: [
                  {
                    id: '29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                    name: 'ILSBLU',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/29dc44d2-9cd2-45f5-81b7-4ee81e7c82be',
                  },
                  {
                    id: 'ba2a859c-2324-4274-a086-0b149f58e195',
                    name: 'ACQ',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/ba2a859c-2324-4274-a086-0b149f58e195',
                  },
                  {
                    id: 'd320935a-ab3d-49f7-a289-be33dcf2b304',
                    name: 'Regrade',
                    href:
                      'http://demo-vnext.tmbmarble.com/api/category-projection/v1/category/d320935a-ab3d-49f7-a289-be33dcf2b304',
                  },
                ],
                bundle: false,
                isBundle: false,
                lastUpdate: '2020-06-30T00:26:00.001Z',
                '@baseType': 'ProductOfferingPrice',
                '@type': 'ProductOfferingPrice',
                specCharValueUse: null,
                createdBy: 'catalog admin',
                createdOn: '2020-06-30T00:26:00.001Z',
                lastUpdatedBy: 'catalog admin',
                productOffering: null,
              },
            ],
            validFor: {
              endDateTime: '2020-07-30T00:25:00.001Z',
              startDateTime: '2020-06-30T00:25:00.001Z',
            },
          },
          '@type': 'Allowed',
          '@baseType': null,
          '@schemaLocation': null,
        },
      ],
      category: { id: '9d86a47a-e013-4f75-8c08-ddfd9ad24a26' },
    },
  ],
  signature: {
    contextSignature: '77302cbaecd8b4e538e030da8f0772682cad259ca6c818a4ace42f5f297f5c04',
    cartSignature: 'a26a730573e310ec37ea26861ae984f3c1eccc08f26e775105c63d3c5dfe8d2',
  },
};
